LB-kibana:
  ports:
  - 5601:5601
  tty: true
  image: rancher/load-balancer-service
  links:
  - org-kibana:org-kibana
  stdin_open: true
org-kibana:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: kibana
  volumes:
  - /data/source/:/opt/kibana/config/
  stdin_open: true

